#!/usr/bin/env bash

set -e
if [ -z "$TRAVIS" ] ; then
    PREFIX=".ci-env/bin/"
fi

"${PREFIX}pep8" aomi
"${PREFIX}pylint" --rcfile=/dev/null aomi
coverage run -a --include 'aomi/*' "${PREFIX}nose2"
"${PREFIX}bandit" -r aomi
"${PREFIX}vulture" aomi
