#!/usr/bin/env bash

set -e
SCRIPTDIR=$( cd ${0%/*} && pwd)
ROOTDIR=${SCRIPTDIR%/*}

if [ -z "$TRAVIS" ] ; then
    PREFIX="${ROOTDIR}/.ci-env/bin/"
fi

"${PREFIX}pep8" aomi
"${PREFIX}pylint" --rcfile=/dev/null aomi
COVERAGE_FILE="${ROOTDIR}/.coverage" "${PREFIX}nose2" -C aomi --coverage "${ROOTDIR}/aomi"
"${PREFIX}bandit" -r aomi
"${PREFIX}vulture" aomi
