#!/bin/sh

set -e

problems() {
    echo "Error: ${1}"
    exit 1
}

if [ ! -e "/.vault-token" ] && \
       [ -z "$VAULT_TOKEN" ] &&
       ([ -z "$VAULT_USER_ID" ] && [ -z "$VAULT_APP_ID" ]) && \
           [ ! -e "/.aomi-app-token" ] ; then
    problems "Unable to find any known Vault authentication hints"
fi
export VAULT_TOKEN_FILE="/.vault-token"
export AOMI_APP_FILE="/.aomi-app-token"

ACTION="$1"

if [ -z "$ACTION" ] ; then
    echo "aomi docker container ${VERSION}"
    aomi
    exit 1
fi
ARGS="$*"

if [ -d "/app" ] ; then
    cd /app || exit 1
fi
/usr/local/bin/aomi $ARGS
