#!/usr/bin/env bash
set -e

if [ -z "$GUDRUN_TRAVIS_URL" ] || \
       [ -z "$TRAVIS_BUILD_ID" ] || \
       [ -z "$TRAVIS_REPO_SLUG" ] ; then
    echo "must be run in travis"
    exit 1
fi

if [ -z "$VAULT_ADDR" ] ; then
    echo "must have a vault"
    exit 1
fi

PRE_HASH="${TRAVIS_BUILD_ID}|${TRAVIS_REPO_SLUG}"
HASH="$(echo -n "$PRE_HASH" | shasum -a 256 | cut -f 1 -d ' ')"
TMP="/tmp/gvt-${RANDOM}"
curl -s -H "Content-Type: text-plain" \
     -X POST \
     --data-raw "$HASH" \
     "$GUDRUN_TRAVIS_URL" > "$TMP"
ROLE_ID=$(cut -f 1 -d ',' < "$TMP")
SECRET_ID=$(cut -f 2 -d ',' < "$TMP")
rm -f "$TMP"
vault write \
      auth/approle/login \
      role_id="$ROLE_ID" \
      secret_id="$SECRET_ID" > "$TMP"
