#!/usr/bin/env bash

TESTS="a_smoke environment exec_context seed template"
VAULT_TESTS="aws"

VAULT_VERSION="0.6.1"

set -e

if [ $# == 1 ] ; then
    TEST="$1"
    if [ "$TEST" == "smoke" ] ; then
        TEST="a_smoke"
    fi
fi

SCRIPT_DIR=$(cd ${0%/*} && pwd)
CIDIR=${SCRIPT_DIR%/*}
BATSGIT="${CIDIR}/.bats-git"
BATSBIN="${CIDIR}/.bats"
. "${CIDIR}/.ci-env/bin/activate"
OWD="$PWD"
cd "$CIDIR"
python setup.py install
cd "$OWD"
if [ ! -d "$BATSGIT" ] ; then
    git clone --depth 1 https://github.com/sstephenson/bats.git "$BATSGIT"
fi
if [ ! -d "$BATSBIN" ] ; then
    cd "$BATSGIT"
    ./install.sh "$BATSBIN"
fi

if [ ! -d "${CIDIR}/.vault" ] ; then
    mkdir -p "${CIDIR}/.vault/"
    OS=$(uname -s)
    if [ "$OS" == "Darwin" ] ; then
        URL="https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_darwin_amd64.zip"
    elif [ "$OS" == "Linux" ] ; then
        URL="https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip"
    fi

    wget -O  "/tmp/vault.zip"  "$URL"
    unzip -d "${CIDIR}/.vault" "/tmp/vault.zip"
    chmod +x "${CIDIR}/.vault/vault"
    PATH="${PATH}:${CIDIR}/.vault"
    export PATH
fi

export CIDIR
EXEC_TESTS=""
for a_test in $TESTS ; do
    EXEC_TESTS="${EXEC_TESTS} ${CIDIR}/tests/integration/${a_test}.bats"
done
if [ -e "${CIDIR}/.vault-token" ] ; then
    VAULT_TOKEN=$(cat "${CIDIR}/.vault-token")
fi
if [ -e "${HOME}/.vault-token" ] ; then
    VAULT_TOKEN=$(cat "${HOME}/.vault-token")
fi

if [ ! -z "$VAULT_TOKEN" ] ; then
    echo "Vault token found!"
    export VAULT_TOKEN
    export VAULT_ADDR
    TMP="/tmp/aomi-integration-${RANDOM}"
    vault mounts &> "$TMP" || true
    if grep 'aomi/aws' "$TMP" &> /dev/null ; then
        echo "Vault server seems legit..."
        echo "$VAULT_TOKEN" > "${CIDIR}/.vault-token"
        for a_test in $VAULT_TESTS ; do
            EXEC_TESTS="${EXEC_TESTS} ${CIDIR}/tests/integration/${a_test}.bats"
        done
    fi
    rm "$TMP"
fi

if [ -z "$TEST" ] ; then
    "${CIDIR}/.bats/bin/bats" $EXEC_TESTS
else
    "${CIDIR}/.bats/bin/bats" "${CIDIR}/tests/integration/${TEST}.bats"
fi
