---
title: "aomi"
description: "Opinionlessly Express Opinions on Vault"
google_analytics:
theme: 
github:
  repository_url: "https://github.com/Autodesk/aomi"
  owner_name: "Autodesk"
baseurl: "/aomi"
exclude:
  - "README.md"
